warning: Debugger speedups using cython not found. Run '"/Users/XiangyuW/anaconda3/bin/python3.6" "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.2.201803171248/pysrc/setup_cython.py" build_ext --inplace' to build.
pydev debugger: starting (pid: 1568)
/Users/XiangyuW/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loading data failed!
Err in loading pickle files and the infor is:  [Errno 2] No such file or directory: '/Users/XiangyuW/Google Drive/Research2015/SNMFUKmeans/Code/facedata/face_19x19.mat'


We now try loding data from mat /Users/XiangyuW/Google Drive/Research2015/SNMFUKmeans/Code/facedata/face_19x19.mat!


Error in loading mat file! The infor is:  [Errno 2] No such file or directory: '/Users/XiangyuW/Google Drive/Research2015/SNMFUKmeans/Code/facedata/face_19x19.mat'


Crucial error: Loading data failed!. Abort now!
